TO MAKE  THE CAKE :

water (2 cups)
Heavy Cream (300gm)
vaniall extract(1tsp)
sugar(1cup)
4 eggs
flour(2cups)
coco powder(1/2 cup)
coffe powder(1tablspoon)
pinch of salt
baking powder(1 tsp)
baking soda(1tsp)
compound chocolate(1/4 of a bar)
vegetable oil(2 table spoon)

TO MAKE THE BUTTER CREAM(OPTIONAL):

unsalted butter(1 stick)
powderd sugar (1 cup)
vanilla (1 tsp)
milk (1/2 cup)